name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      database:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: test-e2e-drizzle

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      
      - run: npm ci

      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/test-e2e-drizzle?schema=public"