version: '3'

services:
  postgres:
    image: bitnami/postgresql
    container_name: pluto_postgres-drizzle
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pluto
    volumes:
      - pluto_postgres_drizzle_data:/var/lib/postgresql/data

volumes:
  pluto_postgres_drizzle_data:
